### ISSUE TITLE
The property IngressSpec.ingressClassName is wrongly marked as deprecated

### ISSUE THREAD

**Issue by mkruse** [apple/pkl-k8s#11]
Hi,

It looks like the property IngressSpec.ingressClassName was wrongly marked as deprecated.

see:
https://github.com/apple/pkl-k8s/blob/0913c83aad1bd87247169e52070e90b7d177d2d8/generated-package/api/networking/v1/Ingress.pkl#L62

It may be, that I completly misunderstood the documentation, but according to https://kubernetes.io/docs/concepts/services-networking/ingress/ and https://kubernetes.io/docs/concepts/services-networking/ingress/ the use of this field is the _current_ way to set the name of an ingress class, and the old _deprecated_ way was to use annotations, like

```
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: "gce"
```
